# sonar.organization=<replace with your SonarQube Cloud organization key>
# dont need orginization key

sonar.projectKey=workforceOps
sonar.projectName=workforceOps

sonar.tests=frontend/src/__tests__
sonar.sources=frontend
# my backend is based on springboot maven so i dont need to create sperate project.properties file
# Because the Maven Sonar plugin reads the project configuration directly from pom.xml
# compiles the project, and automatically provides the Java classpath and binaries to SonarQube,
# so a separate sonar-project.properties file is usually unnecessary.