services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"  # Load Prometheus configuration from this file.
      - "--storage.tsdb.path=/prometheus"               # Store all metrics data in the /prometheus directory.
      - "--web.enable-lifecycle"                        # Allow Prometheus config reload without restarting the container.

    networks:
      - monitor
    ports:
      - "9090:9090"

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: always
    volumes:
      - /proc:/host/proc:ro    # Mount host process information as read-only.
      - /sys:/host/sys:ro      # Mount host system information as read-only.
      - /:/rootfs:ro           # Mount the host root filesystem as read-only.
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - monitor
    ports:
      - "9100:9100"

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitor
    ports:
      - "3001:3000"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: always
    volumes:
      - /var/lib/docker/:/var/lib/docker:ro
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/containerd:/var/lib/containerd:ro
    networks:
      - monitor
    ports:
      - "8081:8080"

  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: always
    volumes:
      - ./loki-config.yml:/etc/loki/config.yaml:ro
      - loki-data:/loki
    command: -config.file=/etc/loki/config.yaml
    networks:
      - monitor
    ports:
      - "3100:3100"

  
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: always
    volumes: 
      - ./promtail-config.yml:/etc/promtail/config.yaml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - monitor
    depends_on:
      - loki



networks:
  monitor:
    driver: bridge

volumes:
  prometheus_data:
  grafana-storage:
  loki-data: