name: devsecops

on: 
  push:
    branches:
      - dev

jobs:
  code-quality:
    uses: ./.github/workflows/code-quality.yml

  secret-scaning:
    uses: ./.github/workflows/secret-scaning.yml 

  dependency-scan:
    uses: ./.github/workflows/dependency-scan.yml

  

  

   