name: OWASP ZAP

on:
  workflow_call:

jobs:
  owasp-zap-test:
    runs-on: ubuntu-latest   
    steps:
      - name: Code Checkout 
        uses: actions/checkout@v4

      - name: check secrets
        run: echo " secrets is ${{ secrets.EC2_HOST }}"

      - name: ZAP scan
        uses: zaproxy/action-full-scan@v0.13.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: http://${{ secrets.EC2_HOST }}:3000
          fail_action: false
          allow_issue_writing: false

      
