name: Git Leaks

on:
  workflow_call:

jobs:
  gitLeaks:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # take from very first to last commit 

      - name: Scan Git Leaks
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # dont add this on secrets, git add it automatically, also when we using this kind of secret token we dont use on: pr req. (high chances to get leaks secret)
