# name: Sonar Qube Scan

# on:   
#   workflow_call:

# jobs:
#   sonar-scan-backend:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Code checkout
#         uses: actions/checkout@v6
#         with: 
#           fetch-depth: 0

#       - name: SonarQube scan
#         uses: SonarSource/sonarqube-scan-action@v8.2.1 # Ex: v4.1.0 or sha1, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
#         env:
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}


name: Sonar Scan

on:
  workflow_call:

jobs:
  sonar-sccan-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v6
        with: 
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: npm # Automatically caches dependencies for faster runner speeds
          cache-dependency-path: frontend/package-lock.json
        
      - name: Install dependencies
        run: npm ci

# optional but recommended 
      - name: Build frontend
        run: npm run build

      - name: Sonar scan
        uses: SonarSource/sonarqube-scan-action@v8.2.1 
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  sonar-scan-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Download Maven dependencies
        working-directory: backend
        run: mvn -B dependency:resolve dependency:resolve-plugins

      - name: Build backend
        working-directory: backend
        run: mvn -B clean verify

      # - name: SonarQube Scan
      #   uses: SonarSource/sonarqube-scan-action@v8.2.1 
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: SonarQube Scan
        working-directory: backend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          mvn -B sonar:sonar \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}




